name:                hephaestus-fm
version:             0.1.0.0
github:              "hephaestus-ng/hephaestus-fm"
license:             BSD3
author:              "Thiago Figueiredo"
maintainer:          "thiagofigueiredo777@gmail.com"
copyright:           "CC"

extra-source-files:
- README.md
- ChangeLog.md

description: Please see the README on Github at <https://github.com/hephaestus-ng/hephaestus-fm#readme>

dependencies:
- base >= 4.7 && < 5
- pretty-tree
- lens
- containers
- parsec
- HUnit

library:
  source-dirs: src

executables:
  hephaestus-fm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hephaestus-fm

tests:
  hephaestus-fm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hephaestus-fm
